### ISSUE TITLE
Use HSV interpolation instead of RGB

### ISSUE THREAD

**Issue by strafe** [WilsontheWolf/eliza#3]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/15663890/99306041-7fb31380-284c-11eb-8a63-c6bb5f141d0a.png">

RGB interpolation between two colours kind of sucks because it gets very muddy in the middle, HSV on the other hand does what most people would expect as you interpolate hue only.

**Comment by WilsontheWolf** [comment]
Thanks for this. Now I know what to google.

**Comment by WilsontheWolf** [comment]
Looking much nicer thank you so much!
![looks good](https://cdn.discordapp.com/attachments/519997113652871181/778097190748028928/image0.png)

**Comment by strafe** [comment]
@WilsontheWolf no problem! Looks great, thanks for implementing it so quickly.
